<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV0vOxxU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV0vOxxU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV0vOxxU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV0vOxxU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV0vOxxU\App_KernelDevDebugContainer([
    'container.build_hash' => 'V0vOxxU',
    'container.build_id' => '0ac74bda',
    'container.build_time' => 1596231975,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV0vOxxU');
